### ISSUE TITLE
Won't compile with template haskell >= 2.18.0.0

### ISSUE THREAD

**Issue by raineszm** [parsonsmatt/exception-via#1]
The type signature for `ConP` changeed in template Haskell 2.18.0.0 to include a list of type applications https://hackage.haskell.org/package/template-haskell-2.18.0.0/changelog.

I guess this is easy enough to fix with a preprocessor directive. I can submit a pull request if that's an acceptable solution.

**Comment by parsonsmatt** [comment]
CPP is a great solution, thanks!

**Comment by raineszm** [comment]
Cool. I made a pull request (#2 )
